version: '3'
services:
  db:
    image: postgres
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=sinatra
      - POSTGRES_USER=sinatra
      - POSTGRES_PASSWORD=sinatra
    ports:
      - "5432:5432"
  api:
    build: .
    command: bundle exec rackup -p 9292
    volumes:
      - .:/app
    ports:
      - "9292:9292"
    depends_on:
      - db
    links:
      - "db"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=sinatra
      - DATABASE_USER=sinatra
      - DATABASE_PASSWORD=sinatra